target "LivePaperSDKTests" do
  inherit! :search_paths
  pod 'OHHTTPStubs', '~> 5.2.3'
  pod 'OCMock', '~> 3.4'
end

target "LivePaperSample" do
  use_frameworks!
  pod "SVProgressHUD", '~> 2.1.2'
end

target "LivePaperSDK" do
  pod 'HPLinkUtils'
end
